name: Deploy

# Se ejecuta en push a main
on:
  push:
    branches:
      - main

jobs:
  test:
    uses: ./.github/workflows/test.yml

  # DOCKER PUBLISH
  # Si quieres deshabilitarlo, descomenta la línea: if: false
  docker-publish:
    needs: test
    # if: false  # Descomenta para deshabilitar
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    uses: ./.github/workflows/docker-publish.yml
    secrets: inherit  # Pasa todos los secretos automáticamente

  notify-webhook:
    needs: [test, docker-publish]
    runs-on: ubuntu-latest
    if: success()  # Solo se ejecuta si los jobs anteriores fueron exitosos
    steps:
      - name: Notify Portainer
        run: |
          curl -X POST http://portainer.siryus-services.com:9000/api/stacks/webhooks/SAMPLE
        # curl -X POST "${{ secrets.DEPLOY_WEBHOOK_URL }}"