name: üê≥ Smoke Test

on:
  workflow_call:
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python (para tests)
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies for tests
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run logging tests
        run: |
          pytest test/test_logging_config.py -v

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Copiar .env.example como .env
        run: cp .env.example .env

      - name: Start Docker Compose in detached mode
        run: |
          docker-compose up --build -d

      - name: Test endpoint ra√≠z con curl
        run: |
          sleep 5  # Espera a que el contenedor est√© listo
          curl -f http://localhost:3000/ || (docker-compose logs && exit 1)

      - name: Stop Docker Compose
        run: |
          docker-compose down
