name: ðŸ§ª CI Test Suite

on:
  workflow_call:

jobs:
  docker-compose:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Copiar .env.example como .env
        run: cp .env.example .env

      - name: Start Docker Compose in detached mode
        run: |
          docker-compose up --build -d

      # - name: Run tests
      #   run: |
      #     # AquÃ­ puedes ejecutar tus pruebas o validaciones
      #     curl -f http://localhost:8080/ || exit 1

      - name: Stop Docker Compose
        run: |
          docker-compose down
      - name: Stop Docker Compose
        run: |
          docker-compose down
